# fly.toml app configuration file generated for tibia-premium-farm-calculator
# See https://fly.io/docs/reference/configuration/

app = "tibia-premium-farm-calculator"
primary_region = "gru"

[build]
  dockerfile = "server/Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "data"
  destination = "/data"
